---
output: 
  html_document:
    toc: true
    toc_float: true
---
\
\



# Education

__University of Miami,  Division Public Health__  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ *09/2021-05/2026(Expected)* 

Ph.D student in Biostatistics   \ \ \ \ \ \ \ \ \ \ \ \ \   GPA: 4 

__Columbia University, Mailman School of Public Health__  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ *09/2019-05/2021*

Master of Science in Biostatistics (Theory and Method Track)  \ \ \ \ \ \    GPA: 3.88 

__Jilin University, School of Public Health__      \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \     \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ *09/2014-06/2019* 

Information Management & Information System (Medical Information Management)  

Bachelor of Management & Bachelor of Preventive Medicine



# Skills and Courses

**Course**: Probability, Biostatistical Methods (regression, survival analysis, longitudinal analysis), Data Science 1, Data Science for Machine Learning (Regularization, non-linear regression, Classification), Statistical Inference, Epidemiology, Advanced Statistical Computing (Monte Carlo, Optimization Algorithms, Bootstrap, MCMC), SAS,Data Mining, Clinical Trial Methodology, Statistical Genetics Models

**Skills**:
Good command of R, SPSS, SQL, SAS

**Languages**: English, Mandarin 



# Publication


￭ Pallavi Misra,**Sibei LIU**, Xiangfei Meng,
What DNA methylation modifications and/or genetic variations interact with childhood maltreatment in the development of depression: A systematic review, Journal of Affective Disorders [Link](https://pubmed.ncbi.nlm.nih.gov/30999089/)

￭ Muzi Li,**Sibei LIU (co-first author)**, Xiangfei Meng, Interactions of childhood maltreatment and genetic variations in adult depression: A systematic review, Journal of Affective Disorders [Link](https://www.sciencedirect.com/science/article/pii/S0165032720324526)

￭ Tingting Gao et al. including **Sibei LIU**, The Role of School Connectedness and Maladaptive Cognitions in the Association between Stress and Internet Addiction: A Serial Mediation Model, Perspectives in Psychiatric Care [Link](https://onlinelibrary.wiley.com/doi/full/10.1111/ppc.12417)


# Research

## *Machine Learning:*

**New York University: Prediction on Autism status using structural MRI measures **  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \
Supervisor: Dr. Park Hyung\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  *07/2020-Current* 

￭  Cleaned dataset and built a logistic-Lasso model to select 68 features, used selected variables to build tree model and applied Adaboost

￭ Did PCA on all features to account for correlation structure in the brain regions and built SVM and tree based on PCs  

￭ Compare sensitivity and specificity between above models

***
 
## *Meta Analysis and Systematic Review:*

**Columbia University School of Dental Medicine: Meta analysis on several topics** \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 
Supervisor: Prof. Jinzhezhen \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  *07/2020-current* 

￭ Used random effects model to find the pooled effect measures,  examined between-study heterogeneity,  produced forest plots in R(no package used)

￭ Used Leave-one-out cross validation and calculated validate statistics to reproduce a publication 

￭ Checked the Publication bias and drew funnel plot  (no package used) 

￭ Gave presentations to lab members on each above topic


**McGill University : Child Maltreatment and Genetic Variation in Adult Psychopathology: A Systematic Review**        
Supervisor: Dr. Xiangfei Meng \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  \ \ \ \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  *07/2018-10/2018* 

Followed the standard process of systematic review: 

￭ Extracted available data and completed the quality evaluation for the screened paper

￭ Divided and summarized quantitative and qualitative parts

￭ Wrote the Introduction of manuscript, which has been published

***
## *Risk Factor Exploraion:*

**Columbia University School of Public Health: Risk Factors of Myelitis Encephalitis based on three hospitals**  
Supervisor: Dr. Yifei Sun \ \ \ \ \ \ \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  *05/2020-07/2020* 

￭ Outputted the descriptive tables of social and clinical covariates

￭ Imputed the missing data using multiple imputation by chained equations and did logistic regressions to explore risk predictors

￭ Wrote the Statistical Method part manuscript                                                  
                                                 


**Jilin University: The Influencing Factor of Teenager Smoking in Liaoning Province **   
Supervisor: Dr.Lina Jin, Dr.Yan Yao\ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \  \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \  \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \    *03/2018-05/2018*  

￭ Determined the innovative perspective of data analysis

￭ Used the complex sampling pack in SPSS to analyze multistage stratified cluster sampling, including doing the Frequency to describe the data distribution, completing the Chi-square analysis and the logistic analysis to find risk factors of teenager smoking in SPSS

***
# Class Projects

The Class projects are team-worked assignments with instructions in several classes in Columbia, which includs 1) applying algorithms in real problems and performing them in R without using existing packages. 2) builting a github-based website 3) applying statistical methods on real data and finished the report.

The detailed information can be found [here](project.html)

# Honors & Awards

04/2021 HongKong PhD Fellowship Scheme awarded by Hongkong Research Grants Council (Declined)

05/2018 China Scholarship Council- Mitacs Summer Internship funding (35000RMB ) 

09/2017 China National Scholarship in Academic Year 2016-17 awarded by Ministry of Education (0.2%)

09/2016 & 09/2018 The First Scholarship in Academic Years 2015-16 and 2016-17 at Jilin University (5%)

# PDF format of Resume

Download [here](Resume0826-Sibei Liu.pdf)




